<?php

use Creational\abstractFactory\Vehicle\Bike\Bike;
use Creational\abstractFactory\Vehicle\Car\Car;
use Creational\abstractFactory\Vehicle\MountainVehicleFactory;
use Creational\abstractFactory\Vehicle\RoadVehicleFactory;
use PHPUnit\Framework\TestCase;

class VehicleTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testCanCreateMountainCarVehicle()
    {
        $mountainVehicle = new MountainVehicleFactory();
        $mountainCar = $mountainVehicle->createCar();
        $this->assertInstanceOf(Car::class,$mountainCar);
    }

    public function testCanCreateMountainBikeVehicle()
    {
        $mountainVehicle = new MountainVehicleFactory();
        $mountainBike = $mountainVehicle->createBike();
        $this->assertInstanceOf(Bike::class,$mountainBike);
    }

    public function testCanCreateRoadCarVehicle()
    {
        $roadVehicle = new RoadVehicleFactory();
        $roadCar = $roadVehicle->createCar();
        $this->assertInstanceOf(Car::class,$roadCar);
    }

    public function testCanCreateRoadBikeVehicle()
    {
        $roadVehicle = new RoadVehicleFactory();
        $roadBike = $roadVehicle->createBike();
        $this->assertInstanceOf(Bike::class,$roadBike);
    }
}