<?php

use Creational\Factory\Vehicle\BikeFactory;
use Creational\Factory\Vehicle\CarFactory;
use Creational\Factory\Vehicle\Vehicles\Vehicle;
use PHPUnit\Framework\TestCase;

class VehicleTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testCanCreateBike()
    {
        $factory = new BikeFactory();
        $bike = $factory->createVehicle();
        $this->assertInstanceOf(Vehicle::class,$bike);
    }

    public function testCanCreateCar()
    {
        $factory = new CarFactory();
        $car = $factory->createVehicle();
        $this->assertInstanceOf(Vehicle::class,$car);
    }
}