<?php


use Structural\Adapter\USB\TypeC\USBTypeCCharger;
use Structural\Adapter\USB\USBTypeCToAAdapter;
use PHPUnit\Framework\TestCase;

class USBTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testTypeCToTypeAAdapter()
    {
        $typeC = new USBTypeCCharger();
        $adapter = new USBTypeCToAAdapter($typeC);
        $this->assertEquals("Charging using Adapter Type-A",$adapter->chargeWithTypeA());
    }
}