<?php

use Creational\Factory\Furniture\ChairFactory;
use Creational\Factory\Furniture\CoffeeTableFactory;
use Creational\Factory\Furniture\Furnitures\Furniture;
use Creational\Factory\Furniture\SofaFactory;
use PHPUnit\Framework\TestCase;

class FurnitureTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testCanCreateChair()
    {
        $factory = new ChairFactory();
        $furniture = $factory->createFurniture();
        $this->assertInstanceOf(Furniture::class,$furniture);
    }

    public function testCanCreateCoffeeTable()
    {
        $factory = new CoffeeTableFactory();
        $furniture = $factory->createFurniture();
        $this->assertInstanceOf(Furniture::class,$furniture);
    }

    public function testCanCreateSofa()
    {
        $factory = new SofaFactory();
        $furniture = $factory->createFurniture();
        $this->assertInstanceOf(Furniture::class,$furniture);
    }
}